version: "3.9"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amenageur
    ports: ["3306:3306"]
    volumes: ["dbdata:/var/lib/mysql"]
volumes:
  dbdata: {}
